on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node-version}}
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: action/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - run: npm ci
      - name: serverless deploy
      - uses: serverless/github-action@master
      

          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

























# name: Deploy Lambda
# on:
#   push:
#     branches:
#       - main
# jobs:
#   deploy:
#     name: deploy
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [12.x]
#       steps:
#       - uses: action/checkout@v2
#       - name: Use Node.js ${{matrix.node-version}}
#         uses: action/setup-node@v1
#         with:
#           node-version: ${{matrix.node-version}}
#       - run: npm ci
#       - name: serverless deploy
#         uses: serverless/github-action@master
#         with:
#           args: deploy
#         env:
#           AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
#           AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}